#!/usr/bin/env bash
# ufw firewall and setup web traffic rules

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp 
sudo ufw allow 443/tcp
sudo ufw enable
